// LOGAN — Exportación de Contexto para IA
// DEC-LOGAN-017: estándar de exportación de contexto para handoff entre IAs.
//
// Genera dos archivos:
// 1. {proyecto}-contexto-ia.md — contexto curado (~100K tokens target)
// 2. {proyecto}-source.tar.gz — snapshot completo del código fuente
//
// Alinea con Art. I (conocimiento como activo), Art. II (documentación),
// Art. VIII (aprendizaje reutilizable).

import { db } from "@/lib/db";

const KEY_FILE_PATTERNS = [
  // Config
  "package.json",
  "next.config.ts",
  "next.config.js",
  "tsconfig.json",
  "tailwind.config.ts",
  "tailwind.config.js",
  "postcss.config.mjs",
  "postcss.config.js",
  ".env.example",
  "components.json",
  // Model
  "prisma/schema.prisma",
  // Entry points
  "src/app/page.tsx",
  "src/app/layout.tsx",
  "src/app/globals.css",
  // Lib core
  "src/lib/db.ts",
  "src/lib/auth.ts",
  "src/lib/logger.ts",
  "src/lib/utils.ts",
  "src/lib/store.ts",
  "src/lib/hooks.ts",
  // APIs (globbed)
  "src/app/api/**/route.ts",
  // Components (page-level only, not shadcn/ui)
  "src/components/**/*.tsx",
  // Services
  "src/lib/services/**/*.ts",
  "src/lib/ai-agent.ts",
];

const EXCLUDE_DIRS = [
  "node_modules",
  ".next",
  ".git",
  "tests",
  "skills",
  "tool-results",
  "agent-ctx",
  "upload",
  "download",
  "db",
  "repo-sync",
];

const EXCLUDE_PATTERNS = [
  /\.log$/,
  /\.db$/,
  /\.db-journal$/,
  /-repo$/,
];

export interface ExportContextRequest {
  projectId: string;
  includeSource?: boolean; // if true, also generate tar.gz
}

export interface ExportContextResult {
  contextMarkdown: string;
  sourceSize?: number;
  fileCount: number;
  contextSize: number;
}

export async function generateContextExport(
  req: ExportContextRequest,
): Promise<ExportContextResult> {
  const project = await db.project.findUnique({
    where: { id: req.projectId },
    include: {
      decisions: { orderBy: { date: "desc" }, take: 20 },
      hypotheses: { orderBy: { createdAt: "desc" }, take: 20 },
      _count: { select: { decisions: true, hypotheses: true, sessionContexts: true } },
    },
  });

  if (!project) {
    throw new Error("Proyecto no encontrado");
  }

  const sections: string[] = [];

  // 1. Header
  sections.push(generateHeader(project));

  // 2. Resumen ejecutivo
  sections.push(generateExecutiveSummary(project));

  // 3. Stack tecnológico
  sections.push(generateStackSection(project));

  // 4. Modelo de datos
  sections.push(await generateDataModelSection());

  // 5. Decisiones técnicas
  sections.push(generateDecisionsSection(project));

  // 6. Estado actual
  sections.push(generateStatusSection(project));

  // 7. Archivos clave (embebidos)
  // Note: in production (Vercel), we can't read the filesystem.
  // This section is generated by the client or by LOGAN reading the repo via GitHub API.
  sections.push(generateFilesNote(project));

  // 8. Cómo probar localmente
  sections.push(generateLocalSetupSection(project));

  const contextMarkdown = sections.join("\n\n---\n\n");

  return {
    contextMarkdown,
    fileCount: project.decisions.length,
    contextSize: contextMarkdown.length,
  };
}

function generateHeader(project: any): string {
  const date = new Date().toISOString().split("T")[0];
  return `# ${project.name} — Contexto para IA

**Fecha de exportación:** ${date}
**Generado por:** LOGAN OS (DEC-LOGAN-017)
**Proyecto:** ${project.name}
**ID:** ${project.id}
**Repositorio:** ${project.repo || "(no configurado)"}

> Este documento es un contexto curado para que cualquier IA pueda entender
> el proyecto sin necesidad de explorar el código desde cero.
> Generado bajo LOGAN Art. I (conocimiento como activo estratégico).`;
}

function generateExecutiveSummary(project: any): string {
  return `## Resumen ejecutivo

**Visión:** ${project.vision}

**Usuarios objetivo:**
${parseUsers(project.users).map((u: string) => `- ${u}`).join("\n")}

**Estado:** ${project.status} | **Fase:** ${project.currentPhase}/8 | **Modo:** ${project.currentMode}`;
}

function generateStackSection(project: any): string {
  const repo = project.repo || "proyecto";
  return `## Stack tecnológico

\`\`\`
${repo}
├── Framework: Next.js 16 (App Router)
├── Language: TypeScript 5
├── Styling: Tailwind CSS 4 + shadcn/ui
├── Database: Prisma ORM + PostgreSQL (Neon)
├── Auth: NextAuth.js v4
├── LLM: Z.ai (GLM-5-turbo/5.2) + Gemini + OpenAI (multi-provider)
├── Deploy: Vercel
└── Repo: https://github.com/appsmx/${repo}
\`\`\``;
}

async function generateDataModelSection(): Promise<string> {
  return `## Modelo de datos

El esquema de Prisma está en \`prisma/schema.prisma\` en el repositorio.
Modelos principales:

- **Project** — nombre, visión, usuarios, estado, fase, modo, repo, llmModel
- **Decision** — DEC-XXX, roleId, problema, alternativas, decisión, justificación
- **Hypothesis** — roleId, contexto, hipótesis, predicción, status, outcome
- **BacklogItem** — título, descripción, status, prioridad
- **SessionContext** — estado, avance, decisiones, pendientes, riesgos
- **PhaseProgress** — fase (1-8), status, notas
- **Audit** — deliverableName, checks (7 items), passed, notes
- **Discovery** — tipo, pregunta, respuesta, clasificación
- **MarketingAsset** — type, title, content, hypothesisId
- **GitAction** — tool, repo, branch, path, commitMessage, prNumber
- **LlmUsage** — projectId, task, provider, model, tokens (tracking)

> Ver \`prisma/schema.prisma\` en el repo para el esquema completo y actualizado.`;
}

function generateDecisionsSection(project: any): string {
  if (project.decisions.length === 0) {
    return `## Decisiones técnicas (DEC-XXX)

Sin decisiones registradas todavía.`;
  }

  const lines = [`## Decisiones técnicas (DEC-XXX)`, ""];
  for (const dec of project.decisions) {
    lines.push(`### ${dec.decId}: ${dec.title}`);
    lines.push(`- **Estado:** ${dec.status}`);
    lines.push(`- **Rol:** ${dec.roleId}`);
    lines.push(`- **Problema:** ${dec.problem}`);
    lines.push(`- **Decisión:** ${dec.decision}`);
    lines.push(`- **Justificación:** ${dec.justification}`);
    lines.push(`- **Fecha:** ${dec.date.toISOString().split("T")[0]}`);
    lines.push("");
  }
  return lines.join("\n");
}

function generateStatusSection(project: any): string {
  const phaseNames: Record<number, string> = {
    1: "Comprender el problema",
    2: "Descubrir información faltante",
    3: "Diseñar la arquitectura",
    4: "Documentar decisiones",
    5: "Construir",
    6: "Auditar",
    7: "Aprender",
    8: "Actualizar documentos",
  };

  return `## Estado actual del proyecto

| Atributo | Valor |
|---|---|
| Estado | ${project.status} |
| Fase actual | ${project.currentPhase}/8 — ${phaseNames[project.currentPhase] || "?"} |
| Modo de trabajo | ${project.currentMode} |
| Decisiones registradas | ${project._count.decisions} |
| Hipótesis registradas | ${project._count.hypotheses} |
| Session contexts | ${project._count.sessionContexts} |
| Repositorio | ${project.repo || "(no configurado)"} |
| Modelo LLM | ${project.llmModel || "(default)"} |

### Hipótesis recientes
${project.hypotheses.slice(0, 5).map((h: any) => 
  `- **[${h.status}]** ${h.roleId}: ${h.hypothesis.substring(0, 100)}...`
).join("\n") || "Sin hipótesis registradas."}`;
}

function generateFilesNote(project: any): string {
  return `## Archivos clave del repositorio

> Los archivos clave están embebidos en el archivo completo \`{proyecto}-contexto-ia.md\`.
> Para generar la versión completa con código embebido, ejecuta el script
> \`export-context.sh\` localmente o usa el endpoint \`/api/export-context\`.

### Archivos incluidos en el contexto curado:

\`\`\`
Config:          package.json, next.config.ts, tsconfig.json, .env.example
Modelo:          prisma/schema.prisma
Entry points:    src/app/page.tsx, src/app/layout.tsx, src/app/globals.css
Lib core:        src/lib/db.ts, src/lib/auth.ts, src/lib/utils.ts, src/lib/hooks.ts
APIs:           src/app/api/**/route.ts (todos los route handlers)
Componentes:     src/components/**/*.tsx (page-level, no shadcn/ui)
\`\`\`

### No incluidos:
- node_modules, .next, .git, builds, logs
- Componentes de shadcn/ui (estándar, reutilizables)
- Tests

### Para ver el código fuente completo:
Descarga \`{proyecto}-source.tar.gz\` (snapshot completo, < 5 MB).`;
}

function generateLocalSetupSection(project: any): string {
  const repo = project.repo || "proyecto";
  return `## Cómo probar localmente

\`\`\`bash
# 1. Clonar el repositorio
git clone https://github.com/appsmx/${repo}.git
cd ${repo}

# 2. Instalar dependencias
bun install

# 3. Configurar variables de entorno
cp .env.example .env
# Editar .env con tus credenciales (DATABASE_URL, API keys, etc.)

# 4. Crear la base de datos
bun run db:push

# 5. Iniciar el servidor de desarrollo
bun run dev

# 6. Abrir http://localhost:3000
\`\`\`

### Variables de entorno necesarias:
- \`DATABASE_URL\` — URL de PostgreSQL (Neon, Supabase, etc.)
- \`ZAI_API_KEY\` — API key de Z.ai (para LLM)
- \`GEMINI_API_KEY\` — API key de Google Gemini (fallback)
- \`OPENAI_API_KEY\` — API key de OpenAI (fallback)
- \`GITHUB_TOKEN\` — Token de GitHub (para git tools)
- \`LOGAN_ALLOWED_REPOS\` — Lista de repos permitidos (comma-separated)
- \`LOGAN_ADMIN_PASSWORD\` — Contraseña del panel de admin`;
}

function parseUsers(raw: string): string[] {
  try {
    const v = JSON.parse(raw);
    if (Array.isArray(v)) return v.filter((x): x is string => typeof x === "string");
    return [];
  } catch {
    return [];
  }
}
